version: '3.4'

services:
  pacifnewsback:
    image: pacifnewsback
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
