# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: npm install
      run: npm ci --omit=dev


    - run: npm run build --if-present

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
        envkey_ACCESS_TOKEN_SECRET: unipacifico
        file_name: ./build/.env
        fail_on_empty: false

    - name: Move node_modules to build
      run: |
        mv node_modules build/node_modules
        mv package.json build/package.json
    
    - name: deploy
      run: (cd build && zip -r ../function.zip .)
    
    - name: Deploy to AWS
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-1
        function_name: pacificNews_back
        zip_file: function.zip

