# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Despliegue de backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Despliegue
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Crear archivo .env
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
        envkey_ACCESS_TOKEN_SECRET: unipacifico
        GOOGLE_APPLICATION_CREDENTIALS: ./firebase.json
        file_name: ./.env
        fail_on_empty: false

    - name: Depliegue a heroku
      uses: akhileshns/heroku-deploy@v3.12.12  # GitHub action name (leave it as it is).
      with:
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        usedocker: true
        docker_build_args: |
            DATABASE_URL
            ACCESS_TOKEN_SECRET
      env:
        ACCESS_TOKEN_SECRET: unipacifico
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

