# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "Realizando test a develop"

on:
  push:
    branches: [ "Develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:

    - uses: actions/checkout@v3

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DATABASE_URL: mysql://developer:pacificode@127.0.0.1:3306/pacificNews_test?schema=public
        envkey_ACCESS_TOKEN_SECRET: unipacifico
        file_name: .env
        fail_on_empty: false

    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        character set server: 'utf8' 
        collation server: 'utf8_general_ci' 
        mysql database: 'pacificNews_test' 
        mysql root password: 'pacificode'
        mysql user: 'developer'
        mysql password: 'pacificode'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: npm test
