# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "Realizando test a develop"

on:
  push:
    branches: [ "Develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:

    - uses: actions/checkout@v3

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        DATABASE_URL: mysql://pacificnews_usr_ex:ESz4gu3abBEiEXue@192.241.155.75:3306/pacificNews?schema=public
        ACCESS_TOKEN_SECRET: unipacifico
        directory: ./
        file_name: .env
        fail_on_empty: false

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: npm test
